# Travis-CI Build for Boo
# see travis-ci.org for details

language: csharp

# Choose a compatible Mono version
mono:
  - 4.2.1

env:
  global:
    # GITHUB_TOKEN=xxxx
    - secure: "WtlJfRgv+SakyU28p9agDZ6NMqAHVzLhqSYpuivySv9gWw/RLkEzCeVFPg1sQ9WsqFvEVYwt5Hcasb2U1NydkUdk6tasqy3D+vtKHbisg8jFy2Wdxffu8b5p8laMB7qKCtaBUyDZhvL2ZKXBYDxtYzut/+nSx6V3bMh/FIvN7Fs="
    - EnableNuGetPackageRestore=true
    - NUNIT_VERSION="2.6.3"
    - NANT_COMMIT="e3644541bf083d8e33f450bfbd1a4147e494769c"
    - MONO_PATH=mono
    - MCS_PATH=mcs

install:
  - ./build-tools/bootstrap

script:
 - ./ci

after_success:
 # Generate a simple distribution file
 - popd
 - cp -r build boo-latest
 - zip boo-latest.zip boo-latest/*
 - mono --debug build/booi.exe scripts/github-release.boo -- unstable boo-latest.zip

# Notify development list when needed
notifications:
 recipients:
   - boolang@googlegroups.com
 email:
   on_success: change
   on_failure: always
